kind: Service
apiVersion: v1
metadata:
  name: service
spec:
  selector:
    project: expense
    environmet: dev
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
---

kind: Pod
apiVersion: v1
metadata:
  name: pod-service
  labels:
    project: expense
    environmet: dev
spec:
  containers:
    - name: nginx
      image: nginx
      
